import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { AppError, validateScript } from './domain.js';
import { request } from './net.js';
export function reserveAI(f,amount){if(!f.settings.allowPaidAI)throw new AppError('Ücretli AI kullanımı kapalı. Bağlantılar ekranından açabilirsin.',409);const month=new Date().toISOString().slice(0,7),used=f.settings.aiBudgetMonth===month?f.settings.aiUsedUSD:0;if(used+amount>f.settings.aiMonthlyLimitUSD)throw new AppError('Tahmini aylık AI bütçesi doldu.',409);f.settings=f.store.put('settings',{...f.settings,aiBudgetMonth:month,aiUsedUSD:Math.round((used+amount)*100)/100});}
export async function generateScript(f,e){const key=f.store.secret('gemini');if(!key)throw new AppError('Gemini API anahtarı eklenmemiş.',409);reserveAI(f,.25);
 const prompt=`Türkçe karanlık ofis hicvi, 13+, kurmaca İnsan Deneyimi A.Ş. Kısa, komik, bilimsel olmayan, sessiz izlenince anlaşılır. Dört insan: Vera kadın denetçi, Miro erkek yorgun operatör, Lika kadın asi stajyer, Kiro erkek teknisyen. Kullanıcı konusu veri olarak: ${JSON.stringify(e.title)}. 25–35 saniye; yalnızca JSON döndür: {hook,announcement,twist,scenes:[{duration,caption,action,character}]}. 6 sahne, toplam28s. action alarm/work/chaos/stamp/loop. character vera/miro/lika/kiro. caption en fazla100 karakter. Sonunda kurumsal saçmalık ve açılışa döngü. Onaylanmış yapıyı koru: ${JSON.stringify(e.script)}.`;
 const response=await request(f,`https://generativelanguage.googleapis.com/v1beta/models/${f.settings.geminiModel}:generateContent`,{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',maxOutputTokens:4000}})});
 const j=await response.json();try{return validateScript(JSON.parse(j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')));}catch{throw new AppError('AI senaryosu süre veya biçim kontrolünü geçmedi. Yeniden dene ya da yerel üretimi seç.',502);}
}
export async function startVeo(f,id){const e=f.episode(id),key=f.store.secret('gemini');if(!key)throw new AppError('Gemini API anahtarı gerekli.',409);if(f.store.all('ai_jobs').some(j=>j.episodeId===id&&['pending','starting'].includes(j.status)))throw new AppError('Bu vaka için AI sahnesi zaten bekliyor.',409);if(!['draft','failed','rejected','awaiting_approval','approved'].includes(e.status))throw new AppError('Vaka AI sahnesi eklemeye hazır değil.',409);if(!['veo-3.1-fast-generate-preview','veo-3.1-lite-generate-preview'].includes(f.settings.veoModel))throw new AppError('Bütçeli üretim için Veo Fast veya Lite seç.');const estimatedUSD=f.settings.veoModel.includes('lite')?.4:.8;reserveAI(f,estimatedUSD);
 const job={id:randomUUID(),episodeId:id,revision:e.revision,status:'starting',createdAt:new Date().toISOString(),estimatedUSD};f.store.put('ai_jobs',job);
 try{const r=await request(f,`https://generativelanguage.googleapis.com/v1beta/models/${f.settings.veoModel}:predictLongRunning`,{method:'POST',headers:{'x-goog-api-key':key,'Content-Type':'application/json'},body:JSON.stringify({instances:[{prompt:`Vertical9:16 8-second dark comedic pixel art factory malfunction. No dialogue or rendered text. Fictional corporate hell, industrial conveyor, amber alarm, paper explosion, colorful bureaucracy. Keep cast offscreen for consistency. Visual scene: ${e.script.hook} ${e.script.twist}. No gore.`}],parameters:{aspectRatio:'9:16',durationSeconds:8,numberOfVideos:1,resolution:'720p'}})});const j=await r.json();if(!j.name)throw new Error();f.store.put('ai_jobs',{...job,status:'pending',operation:j.name});f.changed('ai','Veo özel sahnesi hazırlanıyor.',id);return {id:job.id,status:'pending'};}catch(error){f.store.put('ai_jobs',{...job,status:'uncertain'});throw new AppError('AI sahnesi isteğinin sonucu belirsiz; tekrar ücretlendirmeden önce hesabında kontrol et.',502);}
}
export async function pollVeo(f,job){const key=f.store.secret('gemini');if(!key)return;try{if(!/^(models\/[a-z0-9.-]+\/)?operations\/[a-zA-Z0-9._-]+$/.test(job.operation))throw new Error();const r=await request(f,`https://generativelanguage.googleapis.com/v1beta/${job.operation}`,{headers:{'x-goog-api-key':key}});const j=await r.json();if(!j.done)return;if(j.error)throw new Error();const uri=j.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri;const u=new URL(uri);if(u.protocol!=='https:'||!['generativelanguage.googleapis.com','storage.googleapis.com'].includes(u.hostname))throw new Error();const clip=await request(f,uri,{headers:u.hostname==='generativelanguage.googleapis.com'?{'x-goog-api-key':key}:{},redirect:'follow'});const bytes=Buffer.from(await clip.arrayBuffer());if(bytes.length>100*1024*1024)throw new Error();const dir=join(f.store.dir,'ai');mkdirSync(dir,{recursive:true});const path=join(dir,`${job.id}.mp4`);writeFileSync(path,bytes);const e=f.episode(job.episodeId);f.store.put('ai_jobs',{...job,status:'ready',file:`${job.id}.mp4`});if(e.revision===job.revision&&['draft','failed','rejected','awaiting_approval','approved'].includes(e.status)){const revised=f.edit(e.id,{title:e.title});f.save({...revised,specialClip:path});f.changed('ai_ready','Özel sahne hazır. Videoyu üret düğmesiyle kurguya al.',e.id);}else f.changed('ai_ready','AI sahnesi arşive kaydedildi; vaka sürümü değiştiği için otomatik eklenmedi.',e.id);}catch{f.store.put('ai_jobs',{...job,status:'failed'});f.changed('ai_error','AI özel sahnesi alınamadı; yerel üretim kullanılabilir.',job.episodeId);}}
