import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { AppError, CAST, DEPARTMENTS, IDEAS, DEFAULT_SETTINGS, createEpisode, updateEpisode, approveEpisode, scheduleEpisode, assertApproved } from './domain.js';
import { routeComment } from './comments.js';

const stamp=()=>new Date().toISOString();
export class Factory {
 constructor(store){this.store=store;this.busy=false;this.listeners=new Set();this.controller=null;this.lastSync=0;const saved=store.get('settings','main'),migrated=saved&&!saved.settingsSchemaVersion?{...saved,geminiModel:DEFAULT_SETTINGS.geminiModel,settingsSchemaVersion:DEFAULT_SETTINGS.settingsSchemaVersion}:saved;this.settings=store.put('settings',{...DEFAULT_SETTINGS,...migrated,id:'main'});}
 changed(type,message,id=null){this.store.event(type,message,id);for(const fn of this.listeners)fn();}
 episode(id){const e=this.store.get('episodes',id);if(!e)throw new AppError('Vaka bulunamadı.',404);return e;}
 save(e){return this.store.put('episodes',{...e,updatedAt:stamp()});}
 artifactDir(e){return join(this.store.dir,'media',e.id,`r${e.revision}`);}
 create(input){const e=createEpisode(input,this.store.all('episodes').map(e=>e.title));this.save(e);this.changed('created',`${e.title}: senaryo masasına geldi.`,e.id);return e;}
 edit(id,input){const e=this.save(updateEpisode(this.episode(id),input));this.changed('edited','Senaryo güncellendi; önceki onay kaldırıldı.',id);return e;}
 queue(id){const e=this.episode(id);if(!['draft','failed','rejected','awaiting_approval','approved','scheduled'].includes(e.status))throw new AppError('Vaka zaten işlemde veya yayımlandı.',409);const result=this.save({...e,status:'queued',progress:0,error:null,approvedAt:null,approvalRevision:null,scheduledAt:null,artifacts:null,renderRevision:null});this.changed('queued',`${e.title}: üretim sırasına alındı.`,id);return result;}
 approve(id){let e=this.episode(id);if(!e.artifacts?.video||!existsSync(join(this.artifactDir(e),e.artifacts.video)))throw new AppError('Üretilmiş video dosyası bulunamadı.',409);e=this.save(approveEpisode(e));this.changed('approved','Video onaylandı. Yayın paketi hazır.',id);return e;}
 reject(id){const e=this.episode(id);if(!['awaiting_approval','approved','scheduled'].includes(e.status))throw new AppError('Vaka bu aşamada geri gönderilemez.',409);this.save({...e,status:'rejected',approvedAt:null,approvalRevision:null,scheduledAt:null});this.changed('rejected','Vaka düzenleme için geri gönderildi.',id);}
 schedule(id,at){const e=this.save(scheduleEpisode(this.episode(id),at));this.changed('scheduled',`Yayın planlandı: ${new Date(at).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'})}`,id);return e;}
 requestPublish(id){const e=this.episode(id);assertApproved(e);if(!['approved','scheduled','needs_connection'].includes(e.status))throw new AppError('Yayın işlemi zaten başlatıldı veya tamamlandı.',409);this.save({...e,status:'publish_queued',scheduledAt:null,error:null});this.changed('publish_queued','Onaylı vaka yayın kuyruğuna alındı.',id);}
 recover(){for(const e of this.store.all('episodes')){if(['rendering','scripting','qc','importing'].includes(e.status))this.save({...e,status:'failed',error:'Önceki işlem kesildi. Yeniden üret düğmesiyle devam edebilirsin.'});if(e.status==='publishing')this.save({...e,status:'needs_connection',error:'Yayın sonucu belirsiz. Bağlı hesapta kontrol et; otomatik tekrar gönderilmedi.'});}for(const p of this.store.all('publications'))if(p.status==='publishing')this.store.put('publications',{...p,status:'uncertain',error:'Uygulama yükleme sırasında kapandı; hesabı kontrol et.'});for(const c of this.store.all('comments'))if(c.status==='sending')this.store.put('comments',{...c,status:'uncertain',reason:'Gönderim sırasında uygulama kapandı. Yanıtı platformda kontrol et.'});}
 saveSettings(input){const result={...this.settings};
  for(const key of ['autoReplies','autoProduction','paused','allowPaidAI','youtubeAudited'])if(key in input){if(typeof input[key]!=='boolean')throw new AppError('Ayar değeri geçersiz.');result[key]=input[key];}
  if('aiMonthlyLimitUSD'in input){const n=Number(input.aiMonthlyLimitUSD);if(!Number.isFinite(n)||n<0||n>500)throw new AppError('AI bütçesi 0–500 USD arasında olmalı.');result.aiMonthlyLimitUSD=n;}
  if(input.youtubeVisibility!==undefined){if(!['private','unlisted','public'].includes(input.youtubeVisibility))throw new AppError('Görünürlük geçersiz.');result.youtubeVisibility=input.youtubeVisibility;}
  if(input.dailyHour!==undefined){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(input.dailyHour))throw new AppError('Saat biçimi geçersiz.');result.dailyHour=input.dailyHour;}
  for(const k of ['geminiModel','veoModel'])if(input[k]!==undefined){if(!/^[a-zA-Z0-9._-]{1,100}$/.test(input[k]))throw new AppError('Model adı geçersiz.');result[k]=input[k];}
  if(input.instagramAccountId!==undefined){if(!/^\d{0,40}$/.test(input.instagramAccountId))throw new AppError('Instagram hesap kimliği rakamlardan oluşmalı.');result.instagramAccountId=input.instagramAccountId;}
  if(input.publicMediaBaseUrl!==undefined){const raw=input.publicMediaBaseUrl.trim();if(raw){let u;try{u=new URL(raw);}catch{throw new AppError('Medya adresi geçersiz.');}if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||/^(localhost|127\.|10\.|192\.168\.|\[)/.test(u.hostname))throw new AppError('Medya kökü herkese açık HTTPS adresi olmalı.');}result.publicMediaBaseUrl=raw.replace(/\/$/,'');}
  this.settings=this.store.put('settings',result);this.changed('settings','Fabrika ayarları güncellendi.');return result;
 }
 saveConnections(input){const allowed=['gemini','youtubeAccessToken','youtubeRefreshToken','youtubeClientId','youtubeClientSecret','instagram','ayrshare'];for(const k of Object.keys(input)){if(!allowed.includes(k)||typeof input[k]!=='string'||input[k].length>12000)throw new AppError('Bağlantı alanı geçersiz.');}for(const[k,v]of Object.entries(input))if(v.trim()){this.store.setSecret(k,v.trim());const id=k.startsWith('youtube')?'youtube':k;this.store.put('connections',{id,status:'configured',checkedAt:null});}this.changed('connection','Bağlantı bilgileri kasaya kaydedildi; doğrulama bekleniyor.');}
 disconnect(id){const map={gemini:['gemini'],youtube:['youtubeAccessToken','youtubeRefreshToken','youtubeClientId','youtubeClientSecret'],instagram:['instagram'],ayrshare:['ayrshare']};if(!map[id])throw new AppError('Bağlantı bulunamadı.');for(const k of map[id])this.store.setSecret(k,null);this.store.put('connections',{id,status:'disconnected'});this.changed('connection','Bağlantı kaldırıldı.');}
 connections(){const flags=this.store.connectionFlags();return [{id:'local',name:'Yerel pixel motoru',status:'connected',detail:'API anahtarı gerekmez.'},{id:'gemini',name:'Gemini + Veo',status:flags.gemini?'configured':'disconnected',detail:'Google AI Pro üyeliğinden ayrı API anahtarı gerekir.'},{id:'youtube',name:'YouTube',status:flags.youtubeAccessToken?'configured':'disconnected',detail:'Herkese açık yükleme için uygulama denetimi gerekir.'},{id:'instagram',name:'Instagram',status:flags.instagram?'configured':'disconnected',detail:'Profesyonel hesap ve erişilebilir medya adresi gerekir.'},{id:'ayrshare',name:'Ayrshare yayın servisi',status:flags.ayrshare?'configured':'disconnected',detail:'İsteğe bağlı ücretli servis; bağlı platformlar hesabından gelir.'},{id:'tiktok',name:'TikTok',status:'manual',detail:'Yayın paketi veya bağlı Ayrshare hesabı.'}].map(c=>({...c,...(this.store.get('connections',c.id)||{})}));}
 state(){const episodes=this.store.all('episodes'),comments=this.store.all('comments'),metrics=this.store.all('metrics');return {episodes,comments,metrics,settings:this.settings,connections:this.connections(),publications:this.store.all('publications'),events:this.store.events(),cast:CAST,departments:DEPARTMENTS,ideas:IDEAS.map((i,index)=>({index,title:i[0],department:i[1],character:i[2]})),busy:this.busy,analytics:{views:metrics.length?metrics.reduce((s,m)=>s+(m.views||0),0):null,produced:episodes.filter(e=>e.artifacts).length,published:this.store.all('publications').filter(p=>p.status==='published').length,awaiting:episodes.filter(e=>e.status==='awaiting_approval').length,consultations:comments.filter(c=>c.status==='consult').length},now:stamp()};}
 addComment(input,source='manual'){if(typeof input.text!=='string'||!input.text.trim()||input.text.length>3000)throw new AppError('Yorum 1–3000 karakter olmalı.');if(!['instagram','tiktok','youtube'].includes(input.platform))throw new AppError('Platform geçersiz.');if(source==='remote'&&!input.externalId)throw new AppError('Yorum kimliği gerekli.');const id=source==='remote'?`${input.platform}:${input.externalId}`:randomUUID();const existing=this.store.get('comments',id);if(existing)return existing;let routed=routeComment(input.text);if(source==='manual'&&routed.status==='ready')routed.status='draft';const c={id,platform:input.platform,externalId:source==='remote'?String(input.externalId):null,episodeId:input.episodeId||null,author:String(input.author||'İzleyici').slice(0,100),text:input.text.trim(),source,createdAt:stamp(),...routed};this.store.put('comments',c);this.changed('comment',routed.status==='consult'?'Yeni yorum kararını bekliyor.':'Yorum yanıt taslağı hazır.');return c;}
 resolveComment(id,input){let c=this.store.get('comments',id);if(!c)throw new AppError('Yorum bulunamadı.',404);if(['sent','sending','uncertain','ignored'].includes(c.status))throw new AppError('Bu yorumun kararı tamamlandı veya sonucu belirsiz.',409);if(input.action==='skip')c={...c,status:'ignored'};else if(input.action==='save'){if(typeof input.reply!=='string'||!input.reply.trim()||input.reply.length>1500)throw new AppError('Yanıt 1–1500 karakter olmalı.');c={...c,reply:input.reply.trim()};}else if(input.action==='send'){if(c.source!=='remote')throw new AppError('Bu yorum elle girildi; taslağı kopyalayıp platformda yanıtla.',409);if(input.reply){if(typeof input.reply!=='string'||input.reply.length>1500||!input.reply.trim())throw new AppError('Yanıt geçersiz.');c.reply=input.reply.trim();}c={...c,status:'approved',approvedAt:stamp()};}else throw new AppError('Yorum eylemi geçersiz.');this.store.put('comments',c);this.changed('comment_decision','Yorum kararı kaydedildi.');return c;}
 async tick(render){if(this.busy||this.settings.paused)return;this.busy=true;try{
  const local=new Date().toLocaleString('sv-SE',{timeZone:'Europe/Istanbul'}),day=local.slice(0,10),hour=local.slice(11,16);
  if(this.settings.autoProduction&&day!==this.settings.lastProductionDay&&hour>=this.settings.dailyHour){this.settings=this.store.put('settings',{...this.settings,lastProductionDay:day});const e=this.create({provider:this.store.secret('gemini')&&this.settings.allowPaidAI?'gemini':'local'});this.queue(e.id);}
  let e=this.store.all('episodes').reverse().find(e=>e.status==='queued');
  if(e){this.controller=new AbortController();try{if(e.provider==='gemini'){this.save({...e,status:'scripting',progress:3});const{generateScript}=await import('./providers.js');e={...e,...await generateScript(this,e)};}
    e=this.save({...e,status:'rendering',progress:5});this.changed('rendering','Render kazanı çalışmaya başladı.',e.id);mkdirSync(this.artifactDir(e),{recursive:true});
    const artifacts=await render(e,this.artifactDir(e),{signal:this.controller.signal,onProgress:p=>{this.save({...this.episode(e.id),progress:Math.min(98,Math.round(Number(p)))});for(const fn of this.listeners)fn();}});
    this.save({...this.episode(e.id),status:'awaiting_approval',progress:100,artifacts,renderRevision:e.revision,error:null});this.changed('rendered','Video, kapak ve altyazılar hazır. Önizleme seni bekliyor.',e.id);
   }catch(error){this.save({...this.episode(e.id),status:'failed',error:error instanceof AppError?error.message:'Video üretimi tamamlanamadı. FFmpeg kurulumunu ve boş disk alanını kontrol et.'});this.changed('error','Üretim durdu; yeniden denenebilir.',e.id);}finally{this.controller=null;}return;}
  e=this.store.all('episodes').find(e=>e.status==='publish_queued'||e.status==='scheduled'&&Date.parse(e.scheduledAt)<=Date.now());if(e){const{publishEpisode}=await import('./providers.js');await publishEpisode(this,e);return;}
  const c=this.store.all('comments').find(c=>c.status==='approved'||this.settings.autoReplies&&c.status==='ready');if(c){const{sendReply}=await import('./providers.js');await sendReply(this,c);}
 }finally{this.busy=false;}}
 cancel(id){const e=this.episode(id);if(e.status==='queued'){this.save({...e,status:'draft',progress:0});this.changed('cancel','Üretim sırası iptal edildi.',id);return;}if(['rendering','scripting'].includes(e.status)&&this.controller){this.controller.abort();return;}throw new AppError('Bu vaka için çalışan üretim yok.',409);}
}
